#!/usr/bin/env bash
# Install and configure HAproxy on a lb-01 server.

apt-get -y update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg .
cat >> /etc/haproxy/haproxy.cfg << EOF
frontend front
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    server 804-web-01 35.227.74.128:80 check
    server 804-web-02 34.74.29.177:80 check
EOF
service haproxy restart
