#!/usr/bin/env bash
# This script is dispaying numbers from 1 to 20 and:

i=1
while [ $i -ne 21 ]; do
	echo $i
	case $i in
		4) echo "bad luck from China" ;;
		9) echo "bad luch from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
		(( i++ ))
done
